model:
    arch: icnet_is
data:
    dataset: cityscapes_instance_segmentation
    train_split: train
    val_split: val
    img_rows: 1025
    img_cols: 2049
    path: datasets/cityscapes/
training:
    n_workers: 6
    train_iters: 5000
    batch_size: 12
    val_interval: 5000
    save_interval: 500
    print_interval: 1
    optimizer:
        name: adadelta
        lr: 1.0e-2
    
    loss: 
        name: multi_scale_cross_entropy

    lr_schedule: 
        name: poly_lr
        max_iter: 7000
        decay_iter: 1
        gamma: 0.9
        last_epoch: -1


    momentum: 0.9
    weight_decay: 0.0001
    resume: pretrained_models/icnetBN_cityscapes_trainval_90k.pth
    visdom: False
